apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbUYyYVhKb2MyaGhjbTFoT21aT1pGbFJkWGROTm1RMU5Fa3JUMlU0UkhnMWVFMTFaR1pwTldGTU5IQmpNR2xpV1ZwVWQySjZRV3RsWW5oSGNFdE5RbkpxYVhwcUx5OHlkRkJUUjBVPSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: quay.io
  name: ravirhsharma-pull-secret
type: kubernetes.io/dockerconfigjson