apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- target:
    kind: Deployment
    name: frontend-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/ravirhsharma/frontend:latest
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: https://backend-app-backend-qa.apps.cluster-x24jw.x24jw.sandbox572.opentlc.com/backend